---
title: "S&DS 230 Project"
author: "Matt Shu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prereqs

```{r, message=FALSE, results = 'hide'}
# Hotfix to overcome error found below with Homebrew TBB vs bundled TBB (only needed once): 
# https://github.com/RcppCore/RcppParallel/issues/182
# remotes::install_github("RcppCore/RcppParallel") 
library(tidyverse)
library(RSQLite)
library(RecordLinkage)
library(stringdist)
library(devtools)
library(quanteda)
library(quanteda.textstats)
```

```{r}
conn <- dbConnect(RSQLite::SQLite(), "22-04-29-playback-fm-top-pop.db")
dfSongs <- dbGetQuery(conn, 'SELECT * FROM tracks')
dfArtists <- dbGetQuery(conn, 'SELECT * FROM artists')
dbDisconnect(conn)
```


## Data Cleaning
### Artist Dataset
#### Cleaning + Subset of Interest
```{r}
dfArtists[dfArtists == "nan"] <- NA

# type (Person, Group, Orchestra, more (?))
# area.name <- looks like there are some states here, but mostly countries!
dfArtistsInterest <- dfArtists %>%
   dplyr::select(artist_id, type, area.name, gender) %>%
   # the objects need to be class "data frame" 
   as.data.frame()
```
#### Merge Artists with Songs
```{r}
dfSongsArtists <- merge(dfSongs,dfArtistsInterest,by="artist_id")
```

### Filter out NA's in Important Parameters
```{r Remove Missing}
cleaned_df <-dfSongsArtists %>%
  filter(!is.na(lyrics))  %>%
  filter(!is.na(artist))  %>%
  filter(!is.na(area.name))  %>%
  # filter(!is.na(gender))  %>%
  filter(!is.na(type))  %>%
  as.data.frame()
```

```{r}
print("Pre-Cleaning # Songs")
dim(dfSongs)
print("Post Merge # Songs")
dim(dfSongsArtists)
print("Post-Cleaning Songs Remaining")
dim(cleaned_df)
```

### Gender
```{r}
# 944 artist id
unique(cleaned_df$gender)
cleaned_df <- cleaned_df %>% 
    mutate(gender = replace(gender, gender == "other", "non-binary"))
# Alternative, use recode
cleaned_df <- cleaned_df %>% 
    mutate(gender = replace(gender, is.na(gender), "group"))
cleaned_df %>% count(gender)
# Since the number of non-binary singers is small, we unfortunately remove them as we are unlikely to find strong conclusions about them
cleaned_df <- cleaned_df %>% filter(gender != "non-binary")
dim(cleaned_df)
```

### area.name -> country
```{r}
unique(cleaned_df$area.name)
cleaned_df <- cleaned_df %>% 
    mutate(country = recode(area.name, "Los Angeles" = "United States", "Boston" = "United States", "Malvern" = "United States", "Olympia Fields" = "United States", "Alpharetta" = "United States", "Atlanta" = "United States", "Nordrhein-Westfalen" = "Germany", "Saddle River" = "United States", "Florida" = "United States", "Hollywood" = "United States", "Manhattan" = "United States", "Vancouver" = "Canada", "Portland" = "United States", "Quebec" = "Canada", "New York" = "United States", "Hawaii" = "United States", "Devon" = "United States", "Toronto" = "Canada", "[Worldwide]" = "Worldwide", "London" = "United Kingdom", "British Virgin Islands" = "United Kingdom", "Brooklyn" = "United States", "Ann Arbor" = "United States", "Salt Lake City" = "United States", "Rome" = "Italy", "Nashville" = "United States", "Chicago" = "United States", "Houston" = "United States", "Scotland" = "United Kingdom", "England" = "United Kingdom", "Puerto Rico" = "United States"))
cleaned_df %>% count(country)
cleaned_df <- cleaned_df %>% 
    mutate(region = recode(country, "Austria" = "Non-UK Europe", "Belgium" = "Non-UK Europe", "Austria" = "Non-UK Europe", "Denmark" = "Non-UK Europe", "Finland" = "Non-UK Europe", "France" = "Non-UK Europe", "Germany" = "Non-UK Europe", "Greece" = "Non-UK Europe", "Iceland" = "Non-UK Europe", "Ireland" = "Non-UK Europe", "Italy" = "Non-UK Europe", "Moldova" = "Non-UK Europe", "Netherelands" = "Non-UK Europe", "Norway" = "Non-UK Europe", "Romania" = "Non-UK Europe", "Russia" = "Non-UK Europe", "Switzerland" = "Non-UK Europe", "Sweden" = "Non-UK Europe", "Spain" = "Non-UK Europe", "Netherlands" = "Non-UK Europe", "Senegal" = "Africa", "Guinea" = "Africa", "Jamaica" = "Africa", "Morocco" = "Africa", "South Africa" = "Africa", "Bahamas" = "Non-Canada/US Americas", "Barbados" = "Non-Canada/US Americas", "Jamaica" = "Non-Canada/US Americas", "Colombia" = "Non-Canada/US Americas", "Panama" = "Non-Canada/US Americas", "Saint Vincent and The Grenadines" = "Non-Canada/US Americas", "Japan" = "Misc", "South Korea" = "Misc", "Worldwide" = "Misc", "Philippines" = "Misc", "Australia" = "Oceania", "New Zealand" = "Oceania"))
cleaned_df %>% count(region)
cleaned_df <- cleaned_df %>% 
    mutate(region = recode(region, "Africa" = "Misc", "Non-Canada/US Americas" = "Misc", "Oceania" = "Misc"))
cleaned_df %>% count(region)
```

## Type
```{r}
unique(cleaned_df$type)
cleaned_df %>% count(type)
dim(cleaned_df)
cleaned_df <- cleaned_df %>% filter(type %in% c("Group", "Person"))
dim(cleaned_df)
```

## Filter out Mismatches in Lyrics

```{r Remove Erroneous Lyrics}
# 
cleaned_df$lyrics <- str_replace_all(cleaned_df$lyrics,"[\\s]+", " ")
cleaned_df$cleaned_lyrics <- 
  str_replace_all(cleaned_df$lyrics, 'Chap\\. [0-9]', NA_character_) %>%
  str_replace_all(., 'Listening Log', NA_character_) %>%
  str_replace_all(., 'Favorite Songs Of', NA_character_) %>%
  str_replace_all(., 'Chapter [0-9]', NA_character_) %>%
  str_replace_all(., 'New Music ', NA_character_) %>%
  str_replace_all(., 'Nominees', NA_character_) %>%
  str_replace_all(., 'Best Songs of ', NA_character_) %>%
  str_replace_all(., "[0-9]+ U S", NA_character_) %>% # Court Cases
  str_replace_all(., "[0-9]+ U.S", NA_character_) %>% # Court Cases
  str_replace_all(.,"[ ]+", " ") %>%
  str_replace(., ".*Lyrics", "") %>%
  str_replace(., "[0-9]*Embed$", "")

cleaned_df <- cleaned_df %>%
  filter(!is.na(cleaned_lyrics)) %>%
  filter(levenshteinSim(track, str_match(lyrics, "(.*)Lyrics")[,2]) > .5) %>% # There are some false positives, when there are other languages
  as.data.frame()

# Filter away songs with less than 100 chars, must have been a mistake in lyrics
cleaned_df <- cleaned_df %>% filter(nchar(cleaned_lyrics) > 100)
dim(cleaned_df)
```

## Readability
```{r}
cleaned_corpus <- corpus(
  cleaned_df,
  docid_field = "track_id",
  text_field = "cleaned_lyrics",
  unique_docnames = TRUE
)
```

```{r}
# We use FORCAST because it's one of the only readability metrics that don't look for sentences
cleaned_df$forcast <- textstat_readability(
  cleaned_corpus,
  measure = "FORCAST",
  min_sentence_length = 3,
  max_sentence_length = 10000,
)$FORCAST
cleaned_df$mean_word_syllables <- textstat_readability(
  cleaned_corpus,
  measure = "meanWordSyllables",
  remove_hyphens = TRUE,
  min_sentence_length = 3,
  max_sentence_length = 10000,
)$meanWordSyllables
```

### Check Lyrics
```{r, eval=FALSE}
suspects <- (cleaned_df %>% 
               filter(mean_word_syllables > 2) %>% 
               arrange(mean_word_syllables) %>%
               select(artist, track, cleaned_lyrics, mean_word_syllables))
suspects
for (row in 1:nrow(suspects)) {
  print(paste(suspects[row, "track"], " - ", suspects[row, "artist"], suspects[row, "mean_word_syllables"]))
  print(suspects[row, "cleaned_lyrics"])
}
```

## Filter to Relevant Details

```{r}
subset_df <- cleaned_df %>%
   dplyr::select(year, type, region, gender, last_fm_listeners, artist_appearances, rank, forcast, mean_word_syllables)
subset_df$log_listeners <- log(last_fm_listeners)
subset_df$log_artist_appearances <- log(artist_appearances)
subset_df$log_mean_word_syllables <- log(mean_word_syllables)
attach(subset_df)
```

# Graphics
## Histogram
```{r}
hist(last_fm_listeners, main="Histogram of Last.fm Listeners", xlab="Last.fm Listeners", ylab = "Frequency", cex.main = 1, cex.lab = 1)
```
```{r}
hist(log_listeners, main="Histogram of Log Last.fm Listeners", xlab="Last.fm Listeners", ylab = "Frequency", cex.main = 1, cex.lab = 1)
```
## Scatterplot
```{r}
plot(last_fm_listeners ~ rank, main="", xlab="", ylab = "", cex.main = 1, cex.lab = 1)
```

```{r}
plot(log_listeners ~ rank, main="", xlab="", ylab = "", cex.main = 1, cex.lab = 1)
```

```{r}
plot(last_fm_listeners ~ year, main="", xlab="", ylab = "", cex.main = 1, cex.lab = 1)
```


```{r}
plot(mean_word_syllables ~ year, main="", xlab="", ylab = "", cex.main = 1, cex.lab = 1)
```

## BoxPlot
```{r}
boxplot(mean_word_syllables, main="", xlab="", ylab = "", cex.main = 1, cex.lab = 1)
```

```{r}
boxplot(log_mean_word_syllables, main="", xlab="", ylab = "", cex.main = 1, cex.lab = 1)
```

```{r}
boxplot(mean_word_syllables ~ gender, main="", xlab="", ylab = "", cex.main = 1, cex.lab = 1)
```